name: Check tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  build:
    name: 📲 Build Android Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          key: $gradle-build-cache
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/gradle-build-cache

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        id: run_tests
        run: ./gradlew :app:testDebugUnitTest
        continue-on-error: false
